### ISSUE TITLE
Demo code sometimes throws error 

### ISSUE THREAD

**Issue by LAMike310** [shokai/node-slackbot#2]
I sometimes get an error message when trying to run the script from the ReadMe:

```
throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
      ^
```

TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:110:11)
    at Object.urlParse [as parse](url.js:104:5)
    at WebSocket.initAsClient (/Users/mgnanakone/Desktop/Slackbot/node_modules/node-slackbot/node_modules/ws/lib/WebSocket.js:550:23)
    at new WebSocket (/Users/mgnanakone/Desktop/Slackbot/node_modules/node-slackbot/node_modules/ws/lib/WebSocket.js:74:18)
    at /Users/mgnanakone/Desktop/Slackbot/node_modules/node-slackbot/lib/slackbot.js:93:17
    at IncomingMessage.<anonymous> (/Users/mgnanakone/Desktop/Slackbot/node_modules/node-slackbot/lib/slackbot.js:44:18)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Any idea why that may be happening? Doesn't happen everytime, but happens at least half the time so it's making my script a little unreliable. Any suggestions would be great. Here's the code I'm using:

```
var slackbot = require('node-slackbot');
var bot = new slackbot('<my-token>');
bot.use(function(message, cb) {
  if ('message' == message.type) {
    console.log(message.user + ' said: ' + message.text);
  }
  cb();
});
bot.connect();
```

**Comment by BowlOfSoup** [comment]
Just dropping by to say that this still happens from time-to-time.
